title: Visual Framework Sample Component
label: Sample Local Component
preview: '@preview--elements'
status: beta
variants:
  - name: default
    hidden: true
    context:
      text: and here is some passed text
  - name: another-variant
    hidden: true
    context:
      text: and some passed text from another variant
context:
  component-type: element
